#!/usr/bin/env groovy

def svnRepo = 'svn://svn.xsjme.com/rog2/pirates/trunk/server/thirdparty/protobuf'
def svnCredentialsId = 'subversion'

pipeline {
    agent {
        label "ubuntu:16.04 && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'PROTOBUF_VERSION',
            defaultValue: '3.0.0',
            description: 'See: https://github.com/google/protobuf/releases')
    }
    environment {
        CC  = '/usr/bin/gcc-7'
        CXX = '/usr/bin/g++-7'
        PROTOBUF_VERSION = "${params.PROTOBUF_VERSION}"
        PROTOBUF_PREFIX = "${env.HOME}/thirdparty/protobuf/${params.PROTOBUF_VERSION}"
    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                checkout([$class: 'SubversionSCM',
                    locations: [[
                        credentialsId: svnCredentialsId,
                        remote: svnRepo,
                        local: '.',
                        depthOption: 'files',
                        ignoreExternalsOption: true,
                    ]],
                    quietOperation: false,
                    workspaceUpdater: [$class: 'UpdateUpdater']
                ])
            }
        }
        stage('Build') {
            steps {
                sh './build-linux.sh'
            }
        }
        stage('Archive') {
            steps {
                zip archive: true, dir: env.PROTOBUF_PREFIX, zipFile: "protobuf-${env.PROTOBUF_VERSION}-linux.zip"
            }
        }
    }
}
