#!/usr/bin/env groovy

def gitRepo = 'https://github.com/rog2/lua-ue4.git'

pipeline {
    agent {
        label "ubuntu:18.04 && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'LUA_UE4_VERSION', defaultValue: '5.3.5')
        string(name: 'CC', defaultValue: '')
        string(name: 'MYCFLAGS', defaultValue: '')
        string(name: 'MYLDFLAGS', defaultValue: '')
    }
    environment {
        LUA_UE4_VERSION = "${params.LUA_UE4_VERSION}"
        LUA_UE4_PREFIX  = "${env.HOME}/thirdparty/lua-ue4/${params.LUA_UE4_VERSION}/linux"
        LUA_UE4_ZIP     = "lua-ue4-${params.LUA_UE4_VERSION}-linux.zip"
        CC              = "${params.CC}"
        MYCFLAGS        = "${params.MYCFLAGS}"
        MYLDFLAGS       = "${params.MYLDFLAGS}"
    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        
        stage('Download') {
            steps {
                git gitRepo
            }
        }
        
        stage('Build') {
            steps {
                withCMake('3.12.2') {
                    sh './Build_Linux.sh'
                }
            }
        }

        stage('Archive') {
            steps {
                zip archive: true, dir: env.LUA_UE4_PREFIX, zipFile: env.LUA_UE4_ZIP
            }
        }
    }
}