#!/usr/bin/env groovy

def gitRepo = 'https://github.com/rog2/vcpkg'

// vcpkg triplet, build static library with dynamic CRT (/MD)
def luaArch = 'x64-windows-static-md'

pipeline {
    agent {
        label "windows:10 && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'LUA_VERSION',
            defaultValue: '5.3.4')
    }
    environment {
        LUA_VERSION = "${params.LUA_VERSION}"
        LUA_PACKAGE_DIR = "${env.WORKSPACE}\\packages\\lua_${luaArch}"
        LUA_ZIP = "lua-${params.LUA_VERSION}-windows.zip"
    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                checkout scm: [$class: 'GitSCM',
                    userRemoteConfigs: [[url: gitRepo]],
                    branches: [[name: "refs/tags/lua-${LUA_VERSION}"]]],
                    changelog: false,
                    poll: false
            }
        }
        stage('Build') {
            steps {
                bat 'bootstrap-vcpkg.bat'
                bat "vcpkg install lua:${luaArch}"
            }
        }
        stage('Archive') {
            steps {
                zip archive: true, dir: env.LUA_PACKAGE_DIR, zipFile: env.LUA_ZIP
            }
        }
    }
}
