#!/usr/bin/env groovy

def gitRepo = 'https://github.com/rog2/protobuf-ue4.git'

pipeline {
    agent {
        label "os:mac && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'PROTOBUF_UE4_VERSION',
            defaultValue: '3.6.1')
    }
    environment {
        PROTOBUF_UE4_VERSION             = "${params.PROTOBUF_UE4_VERSION}"
        PROTOBUF_UE4_PREFIX              = "${env.HOME}/thirdparty/protobuf-ue4/${params.PROTOBUF_UE4_VERSION}"
        PROTOBUF_UE4_ZIP                 = "protobuf-ue4-${params.PROTOBUF_UE4_VERSION}-mac.zip"

    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        
        stage('Download') {
            steps {
                git gitRepo
            }
        }
        
        stage('Build') {
            steps {
                sh './Build_Mac.sh'
            }
        }

        stage('Archive') {
            steps {
                zip archive: true, dir: env.PROTOBUF_UE4_PREFIX, zipFile: env.PROTOBUF_UE4_ZIP
            }
        }
    }
}