#!/usr/bin/env groovy

def gitRepo = 'https://github.com/kingsoftgames/protobuf-ue4.git'

pipeline {
    agent {
        label "os:mac && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'PROTOBUF_UE4_VERSION',
            defaultValue: '3.9.2')
        string(name: 'MACOS_DEPLOYMENT_TARGET',
            defaultValue: '10.15')
    }
    environment {
        PROTOBUF_UE4_VERSION             = "${params.PROTOBUF_UE4_VERSION}"
        PROTOBUF_UE4_PREFIX              = "${env.HOME}/thirdparty/protobuf-ue4/${params.PROTOBUF_UE4_VERSION}/mac"
        PROTOBUF_UE4_ZIP                 = "protobuf-ue4-${params.PROTOBUF_UE4_VERSION}-mac.zip"
        PROTOBUF_UE4_MACOS_DEPLOYMENT_TARGET = "${params.MACOS_DEPLOYMENT_TARGET}"
    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        
        stage('Download') {
            steps {
                git gitRepo
            }
        }
        
        stage('Build') {
            steps {
                withCMake('3.12.2') {
                    sh './Build_Mac.sh'
                }
            }
        }

        stage('Archive') {
            steps {
                zip archive: true, dir: env.PROTOBUF_UE4_PREFIX, zipFile: env.PROTOBUF_UE4_ZIP
            }
        }
    }
}