#!/usr/bin/env groovy

def gitRepo = 'https://github.com/kingsoftgames/lua-ue4.git'

pipeline {
    agent {
        label "os:mac && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'LUA_UE4_VERSION',
            defaultValue: '5.3.5')
        string(name: 'IOS_DEPLOYMENT_TARGET',
            defaultValue: '11.0')
    }
    environment {
        LUA_UE4_VERSION             = "${params.LUA_UE4_VERSION}"
        LUA_UE4_PREFIX              = "${env.HOME}/thirdparty/lua-ue4/${params.LUA_UE4_VERSION}/ios"
        LUA_UE4_ZIP                 = "lua-ue4-${params.LUA_UE4_VERSION}-ios.zip"
        LUA_UE4_IOS_DEPLOYMENT_TARGET = "${params.IOS_DEPLOYMENT_TARGET}"
    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        
        stage('Download') {
            steps {
                git gitRepo
            }
        }
        
        stage('Build') {
            steps {
                withCMake('3.12.2') {
                    sh './Build_IOS.sh'
                }
            }
        }

        stage('Archive') {
            steps {
                zip archive: true, dir: env.LUA_UE4_PREFIX, zipFile: env.LUA_UE4_ZIP
            }
        }
    }
}