#!/usr/bin/env groovy

def gitRepo = 'https://github.com/rog2/recastnavigation-ue4'

pipeline {
    agent {
        label "windows:10 && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'RECASTNAVIGATION_UE4_VERSION',
            defaultValue: '4.16')
    }
    environment {
        RECASTNAVIGATION_UE4_VERSION = "${params.RECASTNAVIGATION_UE4_VERSION}"
        RECASTNAVIGATION_UE4_PREFIX = "${env.WORKSPACE}\\_build"
        RECASTNAVIGATION_UE4_ZIP = "recastnavigation-ue4-${params.RECASTNAVIGATION_UE4_VERSION}-windows.zip"
    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                git gitRepo
            }
        }
        stage('Build') {
            steps {
                withCMake('3.10.1') {
                    bat 'build-windows.bat'
                }
            }
        }
        stage('Archive') {
            steps {
                zip archive: true, dir: env.RECASTNAVIGATION_UE4_PREFIX, zipFile: env.RECASTNAVIGATION_UE4_ZIP
            }
        }
    }
}
