#!/usr/bin/env groovy

def gitRepo = 'https://github.com/kingsoftgames/lua-ue4.git'

pipeline {
    agent {
        label "windows:10 && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'LUA_UE4_VERSION',
            defaultValue: '5.3.5')
    }
    environment {
        LUA_UE4_VERSION             = "${params.LUA_UE4_VERSION}"
        LUA_UE4_PREFIX              = "${env.WORKSPACE}\\third-party\\lua-ue4\\${params.LUA_UE4_VERSION}\\windows"
        LUA_UE4_ZIP                 = "lua-ue4-${params.LUA_UE4_VERSION}-windows.zip"

    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        
        stage('Download') {
            steps {
                git gitRepo
            }
        }
        
        stage('Build') {
            steps {
                withCMake('3.12.2') {
                    bat 'Build_Windows.bat'
                }
            }
        }

        stage('Archive') {
            steps {
                zip archive: true, dir: env.LUA_UE4_PREFIX, zipFile: env.LUA_UE4_ZIP
            }
        }
    }
}